<?php
/**
 * @copyright Actra AG - https://www.actra.ch
 * @license   MIT
 */

declare(strict_types=1);

namespace actra\yuf\form;

use actra\yuf\form\component\collection\ErrorCollection;
use actra\yuf\form\renderer\DefaultComponentRenderer;
use actra\yuf\html\HtmlElement;
use actra\yuf\html\HtmlTag;
use actra\yuf\html\HtmlText;
use LogicException;

abstract class FormComponent extends HtmlElement
{
    public readonly ErrorCollection $errorCollection;
    private ?FormComponent $parentFormComponent = null;
    private bool $hasErrors = false;

    public function __construct(
        string $name,
        private ?FormRenderer $renderer = null
    ) {
        $this->errorCollection = new ErrorCollection();
        parent::__construct(name: $name);
    }

    public function addError(
        string $errorMessage,
        bool $isEncodedForRendering
    ): void {
        if ($isEncodedForRendering) {
            $this->addErrorAsHtmlTextObject(errorMessageObject: HtmlText::encoded(textContent: $errorMessage));
        } else {
            $this->addErrorAsHtmlTextObject(errorMessageObject: HtmlText::unencoded(textContent: $errorMessage));
        }
    }

    public function addErrorAsHtmlTextObject(HtmlText $errorMessageObject): void
    {
        $this->errorCollection->add(errorMessageObject: $errorMessageObject);
        $this->setHasErrorsToTrue();
    }

    final protected function setHasErrorsToTrue(): void
    {
        $this->hasErrors = true;
        if (!is_null(value: $this->parentFormComponent)) {
            $this->parentFormComponent->setHasErrorsToTrue();
        }
    }

    public function hasErrors(bool $withChildElements): bool
    {
        return $withChildElements ? $this->hasErrors : $this->errorCollection->hasErrors();
    }

    /**
     * Generate the html-code for this component to be used for output (done by the renderer)
     *
     * @return string : Generated html-code
     */
    public function render(): string
    {
        $htmlTag = $this->getHtmlTag();

        return is_null(value: $htmlTag) ? '' : $htmlTag->render();
    }

    /**
     * Gets the HtmlTag for this component (generated by the renderer)
     * You can also overwrite this method in child objects to directly return a HtmlTag, if you don't want to use a renderer.
     *
     * @return HtmlTag|null : Generated HtmlTag
     */
    public function getHtmlTag(): ?HtmlTag
    {
        $renderer = $this->getRenderer(setDefaultIfNull: true);
        $renderer->prepare();

        return $renderer->getHtmlTag();
    }

    /**
     * Get the renderer for this component and can also optionally set a default renderer if not already set
     *
     * @param bool $setDefaultIfNull : Set to true, if we want to set default renderer, if none is set
     *
     * @return FormRenderer|null : Renderer or null if not set and we don't want to set the default renderer
     */
    public function getRenderer(bool $setDefaultIfNull = false): ?FormRenderer
    {
        if (
            is_null(value: $this->renderer)
            && $setDefaultIfNull
        ) {
            $this->setRenderer(renderer: $this->getDefaultRenderer());
        }

        return $this->renderer;
    }

    public function setRenderer(FormRenderer $renderer): void
    {
        if (!is_null(value: $this->renderer)) {
            throw new LogicException(message: 'You cannot overwrite a renderer which is already set');
        }

        $this->renderer = $renderer;
    }

    public function getDefaultRenderer(): FormRenderer
    {
        return new DefaultComponentRenderer(formComponent: $this);
    }

    final protected function setParentFormComponent(FormComponent $parentFormComponent): void
    {
        $this->parentFormComponent = $parentFormComponent;
    }
}