<?php

/**
 * @copyright Actra AG - https://www.actra.ch
 * @license   MIT
 */

declare(strict_types=1);

namespace actra\yuf\form;

use actra\yuf\form\component\collection\ErrorCollection;
use actra\yuf\form\renderer\DefaultComponentRenderer;
use actra\yuf\html\HtmlElement;
use actra\yuf\html\HtmlTag;
use actra\yuf\html\HtmlText;
use LogicException;
use Override;

abstract class FormComponent extends HtmlElement
{
    public readonly ErrorCollection $errorCollection;
    private ?FormComponent $parentFormComponent = null;
    private bool $hasErrors = false;

    public function __construct(
        string $name,
        private ?FormRenderer $renderer = null,
    ) {
        $this->errorCollection = new ErrorCollection();
        parent::__construct(name: $name);
    }

    public function addError(HtmlText $errorMessage): void
    {
        $this->errorCollection->add(errorMessageObject: $errorMessage);
        $this->setHasErrorsToTrue();
    }

    final protected function setHasErrorsToTrue(): void
    {
        $this->hasErrors = true;
        if ($this->parentFormComponent !== null) {
            $this->parentFormComponent->setHasErrorsToTrue();
        }
    }

    public function hasErrors(bool $withChildElements): bool
    {
        return $withChildElements ? $this->hasErrors : $this->errorCollection->hasErrors();
    }

    /**
     * Generate the html-code for this component to be used for output (done by the renderer)
     *
     * @return string : Generated html-code
     */
    #[Override]
    public function render(): string
    {
        return $this->getHtmlTag()->render();
    }

    /**
     * Gets the HtmlTag for this component (generated by the renderer)
     * You can also overwrite this method in child objects to directly return a HtmlTag, if you don't want to use a
     * renderer.
     *
     * @return HtmlTag : Generated HtmlTag
     */
    public function getHtmlTag(): HtmlTag
    {
        $renderer = $this->getRenderer(setDefaultIfNull: true)
            ?? throw new LogicException(message: 'The component ' . $this->name . ' has no renderer.');

        return $renderer->createHtmlTag();
    }

    /**
     * Get the renderer for this component and can also optionally set a default renderer if not already set
     *
     * @param bool $setDefaultIfNull : Set to true, if we want to set default renderer, if none is set
     *
     * @return FormRenderer|null : Renderer or null if not set and we don't want to set the default renderer
     */
    public function getRenderer(bool $setDefaultIfNull = false): ?FormRenderer
    {
        if (
            $this->renderer === null
            && $setDefaultIfNull
        ) {
            $this->setRenderer(renderer: $this->getDefaultRenderer());
        }

        return $this->renderer;
    }

    public function setRenderer(FormRenderer $renderer): void
    {
        if ($this->renderer !== null) {
            throw new LogicException(message: 'You cannot overwrite a renderer which is already set');
        }

        $this->renderer = $renderer;
    }

    public function getDefaultRenderer(): FormRenderer
    {
        return new DefaultComponentRenderer(formComponent: $this);
    }

    final protected function setParentFormComponent(FormComponent $parentFormComponent): void
    {
        $this->parentFormComponent = $parentFormComponent;
    }

    final protected function getParentFormComponent(): ?FormComponent
    {
        return $this->parentFormComponent;
    }
}
